name: CheckCompileError
on:
  pull_request:
    types: [closed]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULL_REQ_URL: ${{ github.event.pull_request.comments_url }}
  GIT_SHA: ${{ github.sha }}
  GIT_ACTOR: ${{ github.actor }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
          lfs: false

      # 準備
      - name: Ready...
        run: |
          echo Ready...
          echo from $GITHUB_REF
          echo ${{ github.workspace }}

      # Unityを開いてエラーチェック
      - name: Open Unity
        env:
          UNITY_VERSION: 2020.3.18f1
          UNITY_PATH: /Applications/Unity/Hub/Editor/${{UNITY_VERSION}}/Unity.app/Contents/MacOS/Unity
          PROJECT_PATH: ${{ github.workspace }}/CompleErrorCheskTest
        run: |
          echo cheking compile error 
          echo $UNITY_PATH
          echo $PROJECT_PATH
          $UNITY_PATH -quit -batchmode  -projectPath $PROJECT_PATH

      # 失敗メッセージ
      - name: Post Comment GitHub PullRequest Page On Failed
        if: failure()
        env:
          TEXT: "コンパイルエラーが出ています"
        run: |
          curl -X POST \
               -H "Authorization: token ${GITHUB_TOKEN}" \
               -d "{\"body\": \"${TEXT}　${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GIT_SHA} \"}" \
               ${PULL_REQ_URL}

      # 成功メッセージ
      - name: Post Comment GitHub PullRequest Page On Succeed
        if: success()
        env:
          TEXT: "コンパイルチェック問題なし"
        run: |
          curl -X POST \
               -H "Authorization: token ${GITHUB_TOKEN}" \
               -d "{\"body\": \"${TEXT}　${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GIT_SHA} \"}" \
               ${PULL_REQ_URL}
