name: CheckCompileError
on:
  pull_request:
    types: [closed]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULL_REQ_URL: ${{ github.event.pull_request.comments_url }}
  GIT_SHA: ${{ github.sha }}
  GIT_ACTOR: ${{github.actor}}
  UNITY_VERSION: "2020.3.18f1"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
          lfs: false

      # 準備
      - name: Ready...
        run: |
          echo Ready...
          echo from $GITHUB_REF
          echo ${GITHUB_WORKSPACE}

      # 指定のブランチを展開
      - name: Pull target branch
        env:
          GIT_PATH: "/Users/hagiwara.nozomu/workspace/Projects/CompleErrorCheckTest"
          GIT_BRANCH_NAME: ${{ github.base_ref }}
        run: |
          cd $GIT_PATH
          echo git checkout -f $GIT_BRANCH_NAME
          git checkout -f $GIT_BRANCH_NAME
          echo git pull
          git pull

      # Unityを開いてエラーチェック
      - name: Open Unity
        env:
          UNITY_PATH: "/Applications/Unity/Hub/Editor/${{UNITY_VERSION}}/Unity.app/Contents/MacOS/Unity"
          PROJECT_PATH: "/Users/hagiwara.nozomu/workspace/Projects/CompleErrorCheckTest/CompleErrorCheskTest"
        run: |
          echo cheking compile error 
          $UNITY_PATH -quit -batchmode  -projectPath $PROJECT_PATH

      # 失敗メッセージ
      - name: Post Comment GitHub PullRequest Page On Failed
        if: failure()
        env:
          TEXT: "コンパイルエラーが出ています"
        run: |
          curl -X POST \
               -H "Authorization: token ${GITHUB_TOKEN}" \
               -d "{\"body\": \"@${GIT_ACTOR} ${TEXT}　${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GIT_SHA} \"}" \
               ${PULL_REQ_URL}

      # 成功メッセージ
      - name: Post Comment GitHub PullRequest Page On Succeed
        if: success()
        env:
          TEXT: "コンパイルチェック問題なし"
        run: |
          curl -X POST \
               -H "Authorization: token ${GITHUB_TOKEN}" \
               -d "{\"body\": \"@${GIT_ACTOR} ${TEXT}　${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GIT_SHA} \"}" \
               ${PULL_REQ_URL}
