name: ReCheckCompileError
on:
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULL_REQ_URL: ${{ github.event.issue.url }}
  GIT_SHA: ${{ github.sha }}
  GIT_ACTOR: ${{github.actor}}
  UNITY_VERSION: 2020.3.18f1
  PROJECT_PATH: ${{ github.workspace }}/CompleErrorCheskTest

jobs:
  build:
    name: Re Check Compile Error
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/recompile')
    runs-on: self-hosted
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout branch
        env:
          REF: refs/pull/${{ github.event.issue.number }}/merge
        uses: actions/checkout@v3
        with:
          clean: false
          lfs: false
          ref: ${{ REF }}

      # 準備
      - name: Ready
        run: |
          echo Ready
          echo from $GITHUB_REF
          echo at ${{ github.workspace }}

      # Unityを開いてエラーチェック
      - name: Open Unity
        env:
          UNITY_PATH: /Applications/Unity/Hub/Editor/${{env.UNITY_VERSION}}/Unity.app/Contents/MacOS/Unity
        run: |
          echo cheking compile error 
          echo unity path : $UNITY_PATH 
          echo project path : $PROJECT_PATH 
          $UNITY_PATH -quit -batchmode  -projectPath $PROJECT_PATH

      # 失敗メッセージ
      - name: Post Comment GitHub PullRequest Page On Failed
        if: failure()
        env:
          TEXT: "コンパイルエラーが出ています。再度確認する場合は[/recompile]とコメントしてください。"
        run: |
          curl -X POST \
               -H "Authorization: token ${GITHUB_TOKEN}" \
               -d "{\"body\": \"${TEXT}　${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GIT_SHA} \"}" \
               ${PULL_REQ_URL}

      # 成功メッセージ
      - name: Post Comment GitHub PullRequest Page On Succeed
        if: success()
        env:
          TEXT: "コンパイルチェック問題なし"
        run: |
          curl -X POST \
               -H "Authorization: token ${GITHUB_TOKEN}" \
               -d "{\"body\": \"${TEXT}　${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GIT_SHA} \"}" \
               ${PULL_REQ_URL}
